# Generated by Django 5.1.3 on 2024-11-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0004_alter_book_options_remove_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.PositiveIntegerField(),
        ),
    ]
